# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3c2c163c1b0dd987b45c42df9d8d221e5dd2a6b7fbe8e0b87700a242a91d83743eb434cf67620bcaadf4391e522e5cbf6d92fc7bebfb86d4135847f6b0bc60

test:
  secret_key_base: d17dd87c7d35afb32f2d21f835b8d6a34d61cc804055c10f7e5f3edf0f21b9d9e5a31f5d53c19bb8eb942d64a27ec5c6edfec7ba0e6d38bf8e36421bf13730f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
